import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "@cloudscape-design/global-styles/index.css"
import HelpPanel from "@cloudscape-design/components/help-panel";
import SplitPanel from "@cloudscape-design/components/split-panel";
import Flashbar from "@cloudscape-design/components/flashbar";
import SideNavigation from "@cloudscape-design/components/side-navigation";
import BreadcrumbGroup from "@cloudscape-design/components/breadcrumb-group";
import AppLayoutToolbar from "@cloudscape-design/components/app-layout-toolbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "NG Merida",
  description: "Generated by Etalks",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const sideNavigationMenu = [
    {
      type: "section",
      text: "Transactions",
      items: [
        {
          type: "link",
          text: "Search",
          href: "/transactions/search"
        },
        {
          type: "link",
          text: "Dashboard",
          href: "/transactions/dashboard"
        },
      ]
    },
    {
      type: "section",
      text: "Users",
      items: [
        {
          type: "link",
          text: "Accounts",
          href: "/users/accounts"
        },
        {
          type: "link",
          text: "Groups",
          href: "/users/groups"
        },
         {
          type: "link",
          text: "Permissions",
          href: "/users/permissions"
        },
      ]
    },
    // {
    //   type: "link",
    //   text: "Reports",
    //   ref: "reports"
    // },
    {
      type: "section",
      text: "Engine",
      items: [
        {
          type: "link",
          text: "Extensions",
          href: "/engine/extensions"
        },
        {
          type: "link",
          text: "Configuration",
          href: "/engine/configuration"
        },
        {
          type: "link",
          text: "Dashboard",
          href: "/engine/dashboard"
        },
      ]
    },
    {
      type: "section",
      text: "Archive",
      items: [
        {
          type: "link",
          text: "Configuration",
          href: "/archive/configuration"
        },
        {
          type: "link",
          text: "Dashboard",
          href: "/archive/dashboard"
        },
      ]
    },
    {
      type: "section",
      text: "Alarms",
      items: [
        {
          type: "link",
          text: "Dashboard",
          href: "/alarms/dashboard"
        },
        {
          type: "link",
          text: "Configuration",
          href: "/alarms/configuration"
        },
      ]
    }
  ];

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AppLayoutToolbar
          breadcrumbs={
            <BreadcrumbGroup
              items={[
                { text: 'Home', href: '#' },
                { text: 'Service', href: '#' },
              ]}
            />
          }
          navigationOpen={true}
          navigation={
            <SideNavigation
              header={{
                href: '#',
                text: 'Service name',
              }}
              items={sideNavigationMenu}
            />
          }
          notifications={
            <Flashbar
              items={[
                {
                  type: 'info',
                  content: 'This is an info flash message.',
                  id: 'message_1',
                },
              ]}
            />
          }
          toolsOpen={true}
          tools={<HelpPanel header={<h2>Overview</h2>}>Help content</HelpPanel>}
          content={
            children
          }
          splitPanel={<SplitPanel header="Split panel header">Split panel content</SplitPanel>}
        />
      </body>
    </html>
  );
}
